import { FaqStruct } from "./types"

export const FAQS: FaqStruct[] = [
  { id: 1, question: 'QUESTION_1', answer: 'ANSWER_1' },
  { id: 2, question: 'QUESTION_2', answer: 'ANSWER_2' },
  { id: 3, question: 'QUESTION_3', answer: 'ANSWER_3' },
  { id: 4, question: 'QUESTION_4', answer: 'ANSWER_4' },
  { id: 5, question: 'QUESTION_5', answer: 'ANSWER_5' },
  { id: 6, question: 'QUESTION_6', answer: 'ANSWER_6' },
  { id: 7, question: 'QUESTION_7', answer: 'ANSWER_7' },
  { id: 8, question: 'QUESTION_8', answer: 'ANSWER_8' },
  { id: 9, question: 'QUESTION_9', answer: 'ANSWER_9' },
  { id: 10, question: 'QUESTION_10', answer: 'ANSWER_10' },
  { id: 11, question: 'QUESTION_11', answer: 'ANSWER_11' },
  { id: 12, question: 'QUESTION_12', answer: 'ANSWER_12' },
  { id: 13, question: 'QUESTION_13', answer: 'ANSWER_13' },
  { id: 14, question: 'QUESTION_14', answer: 'ANSWER_14' },
  { id: 15, question: 'QUESTION_15', answer: 'ANSWER_15' },
  { id: 16, question: 'QUESTION_16', answer: 'ANSWER_16' },
  { id: 17, question: 'QUESTION_17', answer: 'ANSWER_17' },
  { id: 18, question: 'QUESTION_18', answer: 'ANSWER_18' },
  { id: 19, question: 'QUESTION_19', answer: 'ANSWER_19' },
  { id: 20, question: 'QUESTION_20', answer: 'ANSWER_20' },
  { id: 21, question: 'QUESTION_21', answer: 'ANSWER_21' },
  { id: 22, question: 'QUESTION_22', answer: 'ANSWER_22' },
  { id: 23, question: 'QUESTION_23', answer: 'ANSWER_23' },
  { id: 24, question: 'QUESTION_24', answer: 'ANSWER_24' },
  { id: 25, question: 'QUESTION_25', answer: 'ANSWER_25' },
  { id: 26, question: 'QUESTION_26', answer: 'ANSWER_26' },
  { id: 27, question: 'QUESTION_27', answer: 'ANSWER_27' },
  { id: 28, question: 'QUESTION_28', answer: 'ANSWER_28' },
]